language: python

python:
  - 3.3
  - 3.4
  - 3.5
  - 3.6

env:
  - DJANGO=2.0
  - DJANGO=2.1

matrix:
  exclude:
    # Python/Django combinations that aren't officially supported
    - { python: 3.3, env: DJANGO=2.1 }
    - { python: 3.4, env: DJANGO=2.1 }

python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install tox-travis

script:
  - tox
