
# Licensed under the Apache License, Version 2.0 (the "License"). You may not
# use this file except in compliance with the License. A copy of the License is
# located at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# or in the "license" file accompanying this file. This file is distributed on
# an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
# express or implied. See the License for the specific language governing
# permissions and limitations under the License.


# Generated by Django 2.0.4 on 2018-04-26 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("djnexmo", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="smsmessagepart",
            name="data",
            field=models.BinaryField(max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name="smsmessagepart",
            name="keyword",
            field=models.CharField(max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name="smsmessagepart",
            name="text",
            field=models.CharField(max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name="smsmessagepart",
            name="udh",
            field=models.BinaryField(max_length=160, null=True),
        ),
    ]
