
# Licensed under the Apache License, Version 2.0 (the "License"). You may not
# use this file except in compliance with the License. A copy of the License is
# located at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# or in the "license" file accompanying this file. This file is distributed on
# an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
# express or implied. See the License for the specific language governing
# permissions and limitations under the License.


# Generated by Django 2.0.4 on 2018-04-26 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("djnexmo", "0002_auto_20180426_1521")]

    operations = [
        migrations.AlterField(
            model_name="smsmessagepart",
            name="message_id",
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="smsmessagepart", unique_together={("concat_ref", "concat_part")}
        ),
    ]
