
# Licensed under the Apache License, Version 2.0 (the "License"). You may not
# use this file except in compliance with the License. A copy of the License is
# located at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# or in the "license" file accompanying this file. This file is distributed on
# an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
# express or implied. See the License for the specific language governing
# permissions and limitations under the License.


# Generated by Django 2.0.4 on 2018-04-30 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("djnexmo", "0004_auto_20180427_1517")]

    operations = [
        migrations.AlterModelOptions(
            name="smsmessagepart",
            options={
                "ordering": ("-concat_ref", "concat_part"),
                "verbose_name": "Message Part",
                "verbose_name_plural": "Message Parts",
            },
        )
    ]
